# Generated by Django 3.0.3 on 2020-04-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_likes', models.IntegerField()),
                ('for_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_likes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Likes'),
        ),
    ]
