# Generated by Django 3.0.3 on 2020-04-07 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0006_likes_user_who_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user_who_liked',
        ),
        migrations.AddField(
            model_name='likes',
            name='user_who_liked',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
