# Generated by Django 3.0.3 on 2020-04-07 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0007_auto_20200407_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user_who_liked',
        ),
        migrations.AddField(
            model_name='likes',
            name='user_who_liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
